GET http://localhost:2005/api/viagens

###

POST http://localhost:2005/api/viagens
Content-Type: application/json

{
  "motoristaId": "u.acf960a0-fa03-42eb-aaa2-ef32e3e849d6",
  "data": "13-03-2005",
  "hora": {
    "horas": 12,
    "minutos": 30
  },
  "origem": "Partage Shopping",
  "destino": "Unifacisa - Centro universitário"
}

###

PUT http://localhost:2005/api/viagens/:
Content-Type: application/json

{

}